name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate vimdoc
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: fennelref
          pandoc: reference.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
